version: '3.8'

services:
  db:
    image: postgres:16
    container_name: hono_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hono_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # adminer - простая панель управления базой данных
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres_data:
